<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>::ICH Home::</title>
<link rel="stylesheet" href="./css/cib.css" type="text/css" />

<script language="JavaScript" type="text/javascript">
//--------------- LOCALIZEABLE GLOBALS ---------------
var cid=new Date();
var monthname=new Array("January","February","March","April","May","June","July","August","September","October","November","December");
var TODAY = monthname[cid.getMonth()] + " " + cid.getDate() + ", " + cid.getFullYear();
//---------------   END LOCALIZEABLE   ---------------
</script>
<style type="text/css">
<!--
.style1 {color: #336600}
-->
</style>
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0" id= "Heads">
  <tr>&nbsp;</tr>
  <tr bgcolor="#99CC66">
  	<td colspan="7" id="dateformat" height="20" bgcolor="#330066">&nbsp;&nbsp;<script language="JavaScript" type="text/javascript">
      document.write(TODAY);	</script>	</td>
  </tr>
<body>
<div class="top_banner">
<div class="top_logo"><img src="images/ich logo.jpg" width="80" height="100"/><img src="images/logo.jpg" width="550" height="100" /></div>
</div>
<div><img src="images/top_nav_bg2.jpg" width="100%" height="8" /></div>
</table>
		<div id="nav">
			<table border="0" cellpadding="0" cellspacing="0" width="100%" id="navigation" >
				<tr>
					<td width="150"><span><font size = 4px><b>Main Menu</b></font></span></td>
				<td rowspan = 11 width="*" >
					<iframe height = "100%" width="100%" scrolling="auto" name="dispframe" frameborder="1" src="home.html">
					</iframe>
				</td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Home</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Staff</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Student</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Courses</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Results</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Reports</a></td>
				</tr>
				<tr>
					<td ><a href="javascript:;" class="navText">Setup</a></td>
				</tr>
				
					
				
				<td ><a href="javascript:;" class="navText2">&nbsp;</a></td>
				</tr>
				<td ><a href="javascript:;" class="navText2">&nbsp;</a></td>
				</tr>
				<td ><a href="javascript:;" class="navText2">&nbsp;</a></td>
				</tr>
			</table>
		</div>
